report was used without .self added alias - more
for some Blender builds (without SSL) it appears necessary to add `import urllib.request` -- I know, it's weird. But if I don't then all the error reporting doesn't even work.

if I don't add `import urllib.request` I get this message
```python
Traceback (most recent call last):
  File "C:\blender_trunk\2.70\scripts\addons\sverchok-master\..\sverchok-master\Tools.py", line
 80, in execute
    version_url = urllib.request.urlopen(url).read().strip().decode()
AttributeError: 'module' object has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\blender_trunk\2.70\scripts\addons\sverchok-master\..\sverchok-master\Tools.py", line
 81, in execute
    except urllib.error.URLError:
AttributeError: 'module' object has no attribute 'error'

location: <unknown location>:-1

location: <unknown location>:-1

```